name: Build Gerfex Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Capacitor Android dependency
        run: npm install @capacitor/android

      - name: Make gradlew executable
        working-directory: native_app_android_base
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: native_app_android_base
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: gerfex-debug-apk
          path: native_app_android_base/app/build/outputs/apk/debug/*.apk
